name: rust proj

services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test"]
      interval: 5s
      timeout: 10s
      retries: 10
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

  migrations:
    image: postgres:16-alpine
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    volumes:
      - ./sql:/sql
    command: [ "sh", "-c", "/sql/bin/update-db.sh && echo 'Migrations completed!'" ]
    networks:
      - app-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: test-rust:1.0.0
    ports:
      - "127.0.0.1:8080:8080"
    depends_on:
      - postgres
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  pgdata:
