FROM python:3.11-alpine

WORKDIR /usr/share/app

COPY requirements/ requirements/

RUN pip install --no-cache-dir -r requirements/backend.in

COPY .. .

EXPOSE 8080

ENTRYPOINT ["uvicorn"]
CMD ["spaceship.main:app", "--host=0.0.0.0", "--port=8080"]